apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadjaoz3312-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadjaoz3312-tenant-component
    app.kubernetes.io/part-of: loadjaoz3312-tenant-app
  name: loadjaoz3312-tenant-component
  namespace: loadjaoz3312-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: loadjaoz3312-tenant-component
status:
  loadBalancer: {}
